// <auto-generated />
namespace IAUECProfessorsEvaluation.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeEvaluationPropType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeEvaluationPropType));
        
        string IMigrationMetadata.Id
        {
            get { return "202001221316508_changeEvaluationPropType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
