// <auto-generated />
namespace IAUECProfessorsEvaluation.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_ServiceUsersMapping2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_ServiceUsersMapping2));
        
        string IMigrationMetadata.Id
        {
            get { return "202003010735549_Create_ServiceUsersMapping2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
